"""
Audit logging module — implements SOX/PCI-DSS compliant audit logging
with HMAC-SHA256 tamper detection.

Required exports:
    log_event(event_type, **fields) -> dict
        Create, store, and return a compliant audit log entry.
        The entry includes ALL required fields for the event type,
        plus the tamper-detection field ('signature').

    get_log() -> list[dict]
        Return all stored audit log entries.

    verify_log(entries) -> list[int]
        Return indices of entries that fail tamper-detection verification.
        Return an empty list if all entries are valid.

Tamper detection method: HMAC-SHA256 Entry Signature
Required tamper-detection field: 'signature'
"""

import uuid
import hashlib
import hmac
import json
import os
from datetime import datetime, timezone
from typing import Any

# ---------------------------------------------------------------------------
# In-memory audit log store (do not change this to a persistent store)
# ---------------------------------------------------------------------------
_AUDIT_LOG: list[dict] = []

# ---------------------------------------------------------------------------
# Supported event types and their required fields (including universal fields)
# ---------------------------------------------------------------------------
_REQUIRED_FIELDS: dict[str, list[str]] = {
    'config_changed': [
        'event_type', 'log_id', 'user_id', 'timestamp',
        'config_key', 'old_value', 'new_value', 'user_agent',
    ],
    'user_login': [
        'event_type', 'log_id', 'user_id', 'timestamp',
        'ip_address', 'success', 'correlation_id',
    ],
    'report_accessed': [
        'event_type', 'log_id', 'user_id', 'timestamp',
        'report_id', 'report_type', 'request_id',
    ],
    'data_exported': [
        'event_type', 'log_id', 'user_id', 'timestamp',
        'export_format', 'record_count', 'destination', 'user_agent',
    ],
    'payment_initiated': [
        'event_type', 'log_id', 'user_id', 'timestamp',
        'amount', 'currency', 'recipient_account', 'session_id',
    ],
}

# ---------------------------------------------------------------------------
# HMAC key — from environment variable AUDIT_HMAC_KEY, default 'default-key'
# ---------------------------------------------------------------------------
_HMAC_KEY: str = os.environ.get('AUDIT_HMAC_KEY', 'default-key')

# Fields that are auto-generated by log_event (not required from the caller)
_AUTO_GENERATED: frozenset[str] = frozenset({'event_type', 'log_id', 'signature'})


def _compute_signature(entry_without_sig: dict) -> str:
    """Compute HMAC-SHA256 signature for a canonical JSON representation.

    The entry must NOT contain the 'signature' field when passed to this
    function, as the signature itself is excluded from the canonical form.
    """
    canonical = json.dumps(
        entry_without_sig,
        sort_keys=True,
        separators=(',', ':'),
        ensure_ascii=False,
    )
    return hmac.new(
        _HMAC_KEY.encode('utf-8'),
        canonical.encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()


def _iso8601_utc_now() -> str:
    """Return current UTC time as ISO 8601 string with millisecond precision.

    Format: YYYY-MM-DDTHH:MM:SS.fffZ
    """
    return (
        datetime.now(timezone.utc)
        .strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3]
        + 'Z'
    )


def log_event(event_type: str, **fields: Any) -> dict:
    """Create a compliant audit log entry for the given event_type.

    Steps:
        1. Validate event_type is recognized.
        2. Validate that 'user_id' is provided (required for all event types).
        3. Validate all event-specific required fields are present.
        4. Build the base entry with event_type + log_id (UUID4) +
           auto-generated timestamp (overridable by caller) + caller fields.
        5. Compute 'signature' via canonical JSON → HMAC-SHA256.
        6. Append to _AUDIT_LOG and return the entry.

    Raises:
        ValueError: if event_type is unrecognized, user_id is missing,
                    or any event-specific required field is missing.
    """
    # 1. Validate event type
    if event_type not in _REQUIRED_FIELDS:
        raise ValueError(
            f"Unrecognized event type: '{event_type}'. "
            f"Supported types: {sorted(_REQUIRED_FIELDS.keys())}"
        )

    # 2. user_id is mandatory for ALL event types
    if 'user_id' not in fields:
        raise ValueError(
            f"Event '{event_type}' requires field 'user_id'"
        )

    # 3. Validate all event-specific required fields are present
    #    (excluding auto-generated fields: event_type, log_id, signature)
    required = _REQUIRED_FIELDS[event_type]
    for field in required:
        if field not in _AUTO_GENERATED and field not in fields:
            raise ValueError(
                f"Event '{event_type}' requires field '{field}'"
            )

    # 4. Build the base entry (without signature)
    entry: dict[str, Any] = {
        'event_type': event_type,
        'log_id': str(uuid.uuid4()),
        'timestamp': _iso8601_utc_now(),
    }
    # Merge caller-supplied fields (caller timestamp overrides auto-generated)
    entry.update(fields)

    # 5. Compute and attach the tamper-detection signature
    entry['signature'] = _compute_signature(entry)

    # 6. Persist in-memory and return
    _AUDIT_LOG.append(entry)
    return entry


def get_log() -> list[dict]:
    """Return all stored audit log entries (a shallow copy)."""
    return list(_AUDIT_LOG)


def verify_log(entries: list[dict]) -> list[int]:
    """Verify tamper-detection signature on every entry.

    For each entry, the signature is recomputed from the canonical JSON
    of all fields *except* 'signature' and compared against the stored
    value using constant-time comparison (hmac.compare_digest) to resist
    timing side-channel attacks.  Entries with a missing or mismatched
    signature are considered tampered.

    Returns:
        List of 0-based indices of entries that fail verification.
        An empty list indicates all entries are valid.
    """
    tampered_indices: list[int] = []

    for i, entry in enumerate(entries):
        # Strip the signature field for re-computation
        entry_without_sig = {
            k: v for k, v in entry.items() if k != 'signature'
        }
        expected_sig = _compute_signature(entry_without_sig)

        # Constant-time comparison to resist timing attacks
        if not hmac.compare_digest(
            entry.get('signature', ''),
            expected_sig,
        ):
            tampered_indices.append(i)

    return tampered_indices
